#!/usr/bin/env python3
"""
FritzBox Reboot Script via TR-064 API.

Reads credentials from a .env file and performs a reboot of the
FritzBox router using the TR-064 SOAP interface (no browser needed).

Prerequisite: In the FritzBox UI, enable application access:
    Heimnetz > Netzwerk > Netzwerkeinstellungen >
    "Zugriff fuer Anwendungen zulassen"
    (Home Network > Network > Network Settings > "Allow access for applications")

Can be used standalone or called from fritzbox_reboot.py.

Requirements:
    pip install fritzconnection python-dotenv
"""

import os
import stat
import sys
from pathlib import Path
from urllib.parse import urlparse
from dotenv import load_dotenv
from fritzconnection import FritzConnection
from fritzconnection.core.exceptions import (
    FritzConnectionException,
    FritzAuthorizationError,
)

VERSION = "2.0"
TESTED_FRITZOS = "8.21"

# Load .env from the same directory as this script
env_path = Path(__file__).parent / ".env"
load_dotenv(dotenv_path=env_path)

FRITZBOX_URL = os.getenv("FRITZBOX_URL", "http://fritz.box")
FRITZBOX_USERNAME = os.getenv("FRITZBOX_USERNAME", "")
FRITZBOX_PASSWORD = os.getenv("FRITZBOX_PASSWORD", "")


def _extract_host(url: str) -> str:
    """Extract hostname/IP from a URL or return as-is if already plain."""
    parsed = urlparse(url)
    if parsed.hostname:
        return parsed.hostname
    return url.strip("/")


def print_header():
    print()
    print("=" * 52)
    print(f"  FritzBox Restart (API/TR-064) - Version {VERSION}")
    print(f"  Tested with FritzOS: {TESTED_FRITZOS}")
    print("=" * 52)
    print()


def step(msg: str):
    print(f"  -> {msg}")


def reboot_fritzbox():
    address = _extract_host(FRITZBOX_URL)

    step(f"Connecting to {address} via TR-064 ...")
    fc = FritzConnection(
        address=address,
        user=FRITZBOX_USERNAME,
        password=FRITZBOX_PASSWORD,
    )
    step(f"Connected to {fc.modelname} (FritzOS {fc.system_version}).")

    step("Sending reboot command ...")
    fc.call_action("DeviceConfig1", "Reboot")

    print()
    print("  [OK] FritzBox reboot triggered successfully.")
    print("  The router will restart now. This takes about 1-2 minutes.")
    print()


def generate_curl_script():
    """Generate a standalone curl-based reboot script with inline credentials."""
    address = _extract_host(FRITZBOX_URL)
    user = FRITZBOX_USERNAME or "admin"
    script_path = Path(__file__).parent / "reboot_fritzbox.sh"

    soap_body = (
        '<?xml version="1.0" encoding="utf-8"?>'
        '<s:Envelope s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"'
        ' xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">'
        "<s:Body>"
        '<u:Reboot xmlns:u="urn:dslforum-org:service:DeviceConfig:1"/>'
        "</s:Body>"
        "</s:Envelope>"
    )

    script_content = f"""#!/bin/bash
# FritzBox Reboot via curl (TR-064 SOAP)
# Generated by fritzbox_reboot_api.py
#
# Usage: ./reboot_fritzbox.sh

FRITZBOX_HOST="{address}"
FRITZBOX_PORT="49000"
FRITZBOX_USER="{user}"
FRITZBOX_PASSWORD="{FRITZBOX_PASSWORD}"

echo ""
echo "===================================================="
echo "  FritzBox Reboot (curl/TR-064)"
echo "  Target: $FRITZBOX_HOST:$FRITZBOX_PORT"
echo "===================================================="
echo ""

read -p "  Are you sure you want to reboot your FritzBox? (yes/no): " confirm
if [[ "$confirm" != "yes" && "$confirm" != "y" ]]; then
    echo "  Aborted."
    exit 0
fi

echo ""
echo "  -> Sending reboot command to $FRITZBOX_HOST ..."

HTTP_CODE=$(curl --silent --output /dev/null --write-out "%{{http_code}}" \\
    --digest \\
    --user "$FRITZBOX_USER:$FRITZBOX_PASSWORD" \\
    --header "soapaction: urn:dslforum-org:service:DeviceConfig:1#Reboot" \\
    --header "content-type: text/xml" \\
    --data '{soap_body}' \\
    "http://$FRITZBOX_HOST:$FRITZBOX_PORT/upnp/control/deviceconfig")

if [[ "$HTTP_CODE" == "200" ]]; then
    echo ""
    echo "  [OK] FritzBox reboot triggered successfully."
    echo "  The router will restart now. This takes about 1-2 minutes."
    echo ""
elif [[ "$HTTP_CODE" == "401" ]]; then
    echo ""
    echo "  [ERROR] Authentication failed (HTTP 401)."
    echo "  Please check username and password in this script."
    echo ""
    exit 1
else
    echo ""
    echo "  [ERROR] Unexpected response (HTTP $HTTP_CODE)."
    echo "  Make sure TR-064 is enabled on your FritzBox."
    echo ""
    exit 1
fi
"""

    script_path.write_text(script_content)
    # Make executable (owner rwx, group rx, others rx)
    script_path.chmod(script_path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"  [OK] Curl script saved to: {script_path}")
    print(f"  Run it with: ./reboot_fritzbox.sh")
    print()


if __name__ == "__main__":
    print_header()

    if not FRITZBOX_PASSWORD:
        print(f"  [ERROR] FRITZBOX_PASSWORD is not set.")
        print(f"  Please add your password to: {env_path}")
        sys.exit(1)

    answer = input("  Are you sure you want to reboot your FritzBox? (yes/no): ").strip().lower()
    if answer not in ("yes", "y"):
        print("  Aborted.")
        sys.exit(0)

    print()

    try:
        reboot_fritzbox()

        save = input("  Save reboot command as standalone curl script? (yes/no): ").strip().lower()
        if save in ("yes", "y"):
            print()
            generate_curl_script()

    except FritzAuthorizationError:
        print("\n  [ERROR] Authentication failed.")
        print("  Please check your username and password in .env")
        sys.exit(1)
    except FritzConnectionException as e:
        print(f"\n  [ERROR] Connection failed: {e}")
        print("  Make sure TR-064 is enabled in your FritzBox:")
        print("  Heimnetz > Netzwerk > Netzwerkeinstellungen >")
        print('  "Zugriff fuer Anwendungen zulassen"')
        print("  (Home Network > Network > Network Settings > Allow access for applications)")
        sys.exit(1)
    except Exception as e:
        print(f"\n  [ERROR] {e}")
        sys.exit(1)
